// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oayloknboqllzgbnyjzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9heWxva25ib3FsbHpnYm55anpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTE0MTksImV4cCI6MjA2NTU2NzQxOX0.OVDLoES2opzJRuaOpPP77ORaD99xc4TRynRVXXNEeQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);